require("jquery");
require("angular");
require("angular-resource");
require("angular-local-storage");
require("angular-ui-router");
require("angular-chart.js");
require("angular-sanitize");
require("chart.js");
require("ng-table/bundles/ng-table");
require("ng-table/bundles/ng-table.css");
require("bootstrap-loader");
require("eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css");
require("eonasdan-bootstrap-datetimepicker");
require("ui-select");
require("ui-select/dist/select.min.css");
window.moment = require("moment");
